version: '3.8'

services:
  backend:
    image: anshulmenaria/terrasense-backend
    container_name: node-backend
    ports:
      - "5000:5000"
    restart: always

  frontend:
    image: anshulmenaria/terrasense-admin-panel
    container_name: react-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: always

